image: docker:stable

stages:
  - install
  - package

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  STAGING_REGISTRY: "registry.gitlab.com"
  CONTAINER_TEST_IMAGE: ${STAGING_REGISTRY}/eyfo/${CI_PROJECT_NAME}:commit-${CI_COMMIT_SHA}

install:
  image: node:8
  stage: install
  before_script: 
    - yarn config set cache-folder .yarn
  script:
    - yarn

package:
  stage: package
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  script:
    - docker build -t $CONTAINER_TEST_IMAGE --build-arg buildtime_CI_COMMIT_SHA=`date '+%Y-%m-%d-%H%M'`-${CI_COMMIT_SHA:0:9} .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master-bdbq
  except:
    changes:
      - docker-compose.yml
