FROM node:8.16 AS node_deps
WORKDIR /srv/app
COPY package.json yarn.lock ./
RUN yarn install

FROM ruby:2.5.7-stretch

MAINTAINER OpenSource Connections <quepid_admin@opensourceconnections.com>

# Must have packages
RUN apt-get update -qq && apt-get install -y vim curl git tmux

# Install Node
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get install -y nodejs
RUN apt-get update && apt-get install -y --allow-unauthenticated yarn netcat

RUN yarn global add phantomjs-prebuilt

# Clean environment
RUN apt-get clean all

# Install dependencies
WORKDIR /srv/app
COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY --from=node_deps /srv/app/node_modules ./node_modules/
COPY . .
CMD foreman s
