version: '3'
services:
  mysql:
    container_name: quepid_db
    image: mysql:5.6.37
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  redis:
    container_name: quepid_redis
    image: redis
    ports:
      - 6379:6379

  app:
    container_name: quepid_app
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: registry.gitlab.com/eyfo/quepid:commit-872cd1e5c208816cc739ae09d9faa66dd02fe7b2
    environment:
      - PORT=3000
      - RACK_ENV=production
      - RAILS_ENV=production
      - DB_ADAPTER=mysql2
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=quepid
      - REDIS_URL=redis://redis:6379/1
      - FORCE_SSL=false
      - MAX_THREADS=2
      - WEB_CONCURRENCY=2
      - SECRET_KEY_BASE=a5c2f01dfffc53f78acb2da5c5379c1246fbc97c57dfde2fe7d0c27e66e6552785282cec5dbb82b9548a9d0c46824c5fa041abcff1597cc6ee58647d3e6a0514
    #volumes:
    #  - .:/srv/app
    ports:
      - 3000:3000
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
