version: '3'   # on CircleCI the version and services cause build to puke.
services:
  mysql:
    container_name: quepid_db
    image: mysql:5.6.37
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  redis:
    container_name: quepid_redis
    image: redis
    ports:
      - 6379:6379

  app:
    container_name: quepid_app
    #build:
    #  context: .
    #  dockerfile: Dockerfile.dev
    #image: quepid/app
    image: registry.gitlab.com/eyfo/quepid:commit-1305f38c11d54ff24e0ff0357e67ad4f888fbf5a
    command: foreman s -f Procfile.dev
    environment:
      - PORT=3000
      - RACK_ENV=development
      - RAILS_ENV=development
      - DB_ADAPTER=mysql2
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=quepid
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/srv/app
    ports:
      - 3000:3000
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
